### PR TITLE
[WIP] Prepare code for adding voltage

### PR DESCRIPTION
**Pull request by Eraden**
Add clippy and fmt checks

Prepare code for adding voltage

### CODE REVIEW

**Comment by BoostCookie** [comment]
What is clippy and what do you mean with "adding voltage"?

**Comment by Eraden** [comment]
I'm thinking about adding second binary for this and currently experimenting with project layout

**Review by BoostCookie — APPROVED** [review]
Looks good to me

**Review by r15ch13 — APPROVED** [review]

**Comment by Eraden** [comment]
I decided to merge this because it split project in multiple files which can be later more easily edited.
Also I really want clippy as mandatory part of project.

**Pull request merged**
